#!/bin/bash
set -a

SYSTEM="aurora"
DEPLOYMENT="clustered"
NEKRS_HOME="/flare/datascience/balin/Nek/nekRSv24/exe/nekrsv24"
WORK_DIR=$PWD
VENV_PATH=""
PROJ_ID="datascience"
QUEUE="debug-scaling"
NODES=4
TIME=1:00

if [ ${SYSTEM} == "aurora" ]; then
  module load frameworks
fi

if [[ -z "$VENV_PATH" && ! -d ./_pyg ]]; then
  echo -e "\033[35mA Python venv was not specified, building one now ...\033[m"
  python -m venv --clear _pyg --system-site-packages
  source _pyg/bin/activate
  export TORCH_PATH=$( python -c 'import torch; print(torch.__path__[0])' )
  export LD_LIBRARY_PATH=$TORCH_PATH/lib:$LD_LIBRARY_PATH
  pip install torch_geometric==2.5.3
  VENV_PATH=${PWD}/_pyg/bin/activate
elif [ -d ./_pyg ]; then
  echo -e "\033[35mA Python venv was not specified, but fuond ./_pyg \033[m"
  VENV_PATH=${PWD}/_pyg/bin/activate
fi

echo "Setting up case:"
echo "    system: ${SYSTEM}"
echo "    deployment: ${DEPLOYMENT}"
echo

script_name=nrsqsub_${SYSTEM}
if [ ${DEPLOYMENT} == "colocated" ]; then
  NEKRS_HOME=$NEKRS_HOME WORK_DIR=$WORK_DIR \
  PROJ_ID=$PROJ_ID \
  QUEUE=$QUEUE \
  DEPLOYMENT=$DEPLOYMENT \
  VENV_PATH=$VENV_PATH \
  SIM_NODES=$NODES TRAIN_NODES=$NODES \
  ./${script_name} turbChannel $NODES $TIME
elif [ ${DEPLOYMENT} == "clustered" ]; then
  echo "Running on $NODES total nodes"
  echo "Enter the number of simulation nodes"
  read SIM_NODES
  echo "and trainer nodes to use"
  read TRAIN_NODES
  CPU_BIND_LIST="1:8:16:24:32:40:53:60:68:76:84:92"
  NEKRS_HOME=$NEKRS_HOME WORK_DIR=$WORK_DIR \
  PROJ_ID=$PROJ_ID \
  QUEUE=$QUEUE \
  DEPLOYMENT=$DEPLOYMENT \
  VENV_PATH=$VENV_PATH \
  SIM_NODES=$SIM_NODES TRAIN_NODES=$TRAIN_NODES \
  SIM_CPU_BIND_LIST=$CPU_BIND_LIST TRAIN_CPU_BIND_LIST=$CPU_BIND_LIST \
  SIM_RANKS_PER_NODE=12 TRAIN_RANKS_PER_NODE=12 \
  ./${script_name} turbChannel $NODES $TIME
else
  echo Please select between clustered and colocated deployment of the workflow
fi

